create table notes ( 
    id integer primary key generated by default as identity,
    note_title text not null,
    note_content text not null,
    date_modified timestamp not null default now(),
    folder_id integer references folders(id) on delete set null
)